# -*- coding: utf-8 -*-
"""CFIP_LAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K24_vWkPIf4nEFDqrwRVmRAFTEGnxWbt
"""

# Color Find In Picture_LAB
# LAB(사람 눈에 비슷하게 보여지는 색) 을 기준으로 해서 분류함

from sklearn import cluster
import cv2
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from collections import Counter
import numpy as np

#클러스터(그룹) 갯수
cluster_num = 7

#사진 불러오기
img = cv2.imread("./picture_dataset/picture-6.jpeg")
# print(img.shape) #가로, 세로, 색 채널 순서로 출력

#RGB 변환
rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

print("관찰 이미지")
plt.imshow(rgb)
plt.show()

#LAB 변환
img = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)

#색 채널 갯수와 열 갯수 동일하게 reshape
pix = img.reshape((-1, 3))
# print(pix.shape)

#kmeans 계산
kmeans = KMeans(n_clusters=cluster_num) #몇개의 클러스터(그룹) 으로 나눌지
kmeans.fit(pix)

cluster_means = kmeans.cluster_centers_ #각 클러스터 그룹에서의 색의 평균값

cluster_means = cluster_means.astype(np.uint8)
rgb = cv2.cvtColor(cluster_means.reshape(1, -1, 3), cv2.COLOR_LAB2RGB)
rgb = rgb.reshape(-1, 3)

counts = Counter(kmeans.labels_) # 각 클러스터마다 들어가있는 값의 갯수
sorted_counts = counts.most_common()

color= np.zeros((1,cluster_num,3), dtype=np.uint8)

for i in range(cluster_num):
  color[:, i ] = rgb[ sorted_counts[i][0] ]

plt.imshow(color)
plt.show()

# print(rgb)
# print(sorted_counts)
# print(color)
